# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Pokedex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pokedex
  pod 'Alamofire', '5.4'
#  pod 'AlamofireImage', '4.1'
#  pod 'Kingfisher', '7.0'
  
end
